### ISSUE TITLE
Access-Control-Allow-Origin problem

### ISSUE THREAD

**Issue by cdiaz** [MRokas/PokemonGo-Map-WebUI#2]
XMLHttpRequest cannot load http://cdb9d576.ngrok.io/raw_data. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1337' is therefore not allowed access.

**Comment by MRokas** [comment]
You will have to enable CORS on your server. I've never used ngrok so I've no idea how to do that with ngrok.
